# Generated by Django 5.0.4 on 2025-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardapp',
            name='dashboard_section',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Dashboard section'),
        ),
        migrations.AddField(
            model_name='dashboardapp',
            name='sidebar_section',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Sidebar section'),
        ),
    ]
