# Generated by Django 5.0.4 on 2025-01-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0002_dashboardapp_dashboard_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardapp',
            name='page',
        ),
    ]
