

###  nginx.conf - basic auth / no authrequest

upstream sirene {
    server sirene_app:8001;
}

log_format sirene '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer"';

server {

    listen 80;
    server_name  localhost;
    server_tokens off;
    #error_log /var/log/nginx.error.log debug;
    access_log  /var/log/nginx/access.log  sirene;


    # -----------------------
    # static public
    # -----------------------

    # static in DEV mode are also served by NGINX ; use collectstatic before
    
    location /static/ {
        alias /static_collect/;
    }
    
    location /logo/ {
        alias /logo/;
    }

    # -----------------------
    # apps(s)
    # -----------------------

    # Sirene public page, and static assets
    location / {
        proxy_pass http://sirene;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        real_ip_header X-Real-IP;
        #proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
        proxy_http_version 1.1;
    }




}
