# Generated by Django 5.0.4 on 2024-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SireneConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.SlugField(default='home', max_length=128, verbose_name='Sirene App')),
                ('keyname', models.SlugField(max_length=128, verbose_name='Keyname(*)')),
                ('value', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Value')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('page', models.CharField(blank=True, default='', max_length=1500, verbose_name='Page')),
                ('order', models.IntegerField(default=100, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Sirene Configuration',
                'verbose_name_plural': 'Sirene Configurations',
                'ordering': ['appname', 'page', 'order', 'keyname'],
                'unique_together': {('appname', 'keyname')},
            },
        ),
    ]
