# Generated by Django 5.0.4 on 2024-07-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128, unique=True)),
                ('displayname', models.CharField(blank=True, max_length=500, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('dataformat', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float')], default='string', max_length=32)),
            ],
            options={
                'verbose_name': 'Sirene DataStatic Class',
                'verbose_name_plural': 'Sirene DataStatic Classes',
                'ordering': ['keyname'],
            },
        ),
        migrations.CreateModel(
            name='DataClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128, unique=True)),
                ('displayname', models.CharField(blank=True, max_length=500, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('group_access', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_create', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_delete', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_export', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_import', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_onoff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_read', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_show', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
                ('group_update', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='app_user.sirenegroup')),
            ],
            options={
                'verbose_name': 'Sirene Data Class',
                'verbose_name_plural': 'Sirene Data Classes',
                'ordering': ['keyname'],
            },
        ),
        migrations.CreateModel(
            name='DataStaticValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=2500, null=True)),
                ('order', models.IntegerField(default=100)),
                ('staticname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.datastatic')),
            ],
            options={
                'verbose_name': 'Sirene DataStatic Value',
                'verbose_name_plural': 'Sirene DataStatic Values',
                'ordering': ['staticname', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DataInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128)),
                ('displayname', models.CharField(blank=True, max_length=500, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('data_json', models.TextField(blank=True, max_length=5000, null=True)),
                ('classobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.dataclass')),
            ],
            options={
                'verbose_name': 'Sirene Data Instance',
                'verbose_name_plural': 'Sirene Data Instances',
                'ordering': ['classobj', 'keyname'],
                'unique_together': {('classobj', 'keyname')},
            },
        ),
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128)),
                ('displayname', models.CharField(blank=True, max_length=500, null=True)),
                ('dataformat', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('boolean', 'boolean'), ('json', 'json'), ('sirene_data', 'sirene_data'), ('sirene_group', 'sirene_group')], default='string', max_length=32)),
                ('dataformat_ext', models.CharField(blank=True, max_length=500, null=True)),
                ('default_value', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('order', models.IntegerField(default=100)),
                ('cardinal_min', models.IntegerField(default=0)),
                ('cardinal_max', models.IntegerField(default=1)),
                ('classobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_data.dataclass')),
            ],
            options={
                'verbose_name': 'Sirene Data Schema',
                'verbose_name_plural': 'Sirene Data Schema',
                'ordering': ['classobj', 'keyname', 'order'],
                'unique_together': {('classobj', 'keyname')},
            },
        ),
    ]
