# Generated by Django 5.0.4 on 2024-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Icon'),
        ),
    ]
