# Generated by Django 5.0.4 on 2024-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_dataclass_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
