# Generated by Django 5.0.4 on 2024-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_dataschema_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='order',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
