# Generated by Django 5.0.4 on 2024-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_dataclass_order_dataclass_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='dataformat',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('boolean', 'boolean'), ('ipv4', 'ipv4'), ('json', 'json'), ('sirene_data', 'sirene_data'), ('sirene_group', 'sirene_group')], default='string', max_length=32),
        ),
    ]
