# Generated by Django 5.0.4 on 2024-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_alter_dataschema_dataformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='dataformat',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('boolean', 'boolean'), ('ipv4', 'ipv4'), ('sirene_data', 'sirene_data'), ('sirene_group', 'sirene_group'), ('sirene_user', 'sirene_user'), ('json', 'json'), ('date', 'date'), ('datetime', 'datetime'), ('sirene_static', 'sirene_static')], default='string', max_length=32),
        ),
    ]
