# Generated by Django 5.0.4 on 2024-08-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_alter_dataschema_dataformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
