# Generated by Django 5.0.4 on 2024-09-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0007_dataschema_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='group_show',
            new_name='role_show',
        ),
    ]
