# Generated by Django 5.0.4 on 2024-09-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0008_rename_group_show_dataclass_role_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='group_access',
            new_name='role_access',
        ),
    ]
