# Generated by Django 5.0.4 on 2024-09-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0011_rename_group_create_dataclass_role_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='group_update',
            new_name='role_update',
        ),
    ]
