# Generated by Django 5.0.4 on 2024-09-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0014_rename_group_onoff_dataclass_role_onoff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='group_import',
            new_name='role_import',
        ),
    ]
