# Generated by Django 5.0.4 on 2024-09-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0015_rename_group_import_dataclass_role_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='group_export',
            new_name='role_export',
        ),
    ]
