# Generated by Django 5.0.4 on 2024-09-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0016_rename_group_export_dataclass_role_export'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datainstance',
            index=models.Index(fields=['classobj'], name='app_data_da_classob_c23de8_idx'),
        ),
        migrations.AddIndex(
            model_name='datainstance',
            index=models.Index(fields=['keyname'], name='app_data_da_keyname_f6bb2e_idx'),
        ),
        migrations.AddIndex(
            model_name='datainstance',
            index=models.Index(fields=['is_enabled'], name='app_data_da_is_enab_2cf813_idx'),
        ),
    ]
