# Generated by Django 5.0.4 on 2024-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0017_datainstance_app_data_da_classob_c23de8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastatic',
            options={'ordering': ['keyname'], 'verbose_name': 'Sirene Data Static Class', 'verbose_name_plural': 'Sirene Data Static Classes'},
        ),
        migrations.AlterModelOptions(
            name='datastaticvalue',
            options={'ordering': ['staticname', 'order'], 'verbose_name': 'Sirene Data Static Value', 'verbose_name_plural': 'Sirene Data Static Values'},
        ),
        migrations.AddField(
            model_name='datastaticvalue',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
