# Generated by Django 5.0.4 on 2024-09-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0018_alter_datastatic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastaticvalue',
            options={'ordering': ['datastatic', 'order'], 'verbose_name': 'Sirene Data Static Value', 'verbose_name_plural': 'Sirene Data Static Values'},
        ),
        migrations.RenameField(
            model_name='datastaticvalue',
            old_name='staticname',
            new_name='datastatic',
        ),
    ]
