# Generated by Django 5.0.4 on 2024-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0019_alter_datastaticvalue_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='dataformat',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('boolean', 'boolean'), ('ipv4', 'ipv4'), ('date', 'date'), ('sirene_data', 'sirene_data'), ('sirene_static', 'sirene_static'), ('sirene_group', 'sirene_group'), ('sirene_user', 'sirene_user'), ('datetime', 'datetime'), ('json', 'json')], default='string', max_length=32),
        ),
    ]
