# Generated by Django 5.0.4 on 2024-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0020_alter_dataschema_dataformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainstance',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update'),
        ),
    ]
