# Generated by Django 5.0.4 on 2024-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0021_datainstance_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='count_estimation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='is_bigset',
            field=models.BooleanField(default=False),
        ),
    ]
