# Generated by Django 5.0.4 on 2024-10-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0022_dataclass_count_estimation_dataclass_is_bigset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='dataformat',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('boolean', 'boolean'), ('ipv4', 'ipv4'), ('date', 'date'), ('sirene_data', 'sirene_data'), ('sirene_static', 'sirene_static'), ('sirene_group', 'sirene_group'), ('sirene_user', 'sirene_user'), ('datetime', 'datetime'), ('json', 'json'), ('text', 'text')], default='string', max_length=32),
        ),
    ]
