# Generated by Django 5.0.4 on 2024-07-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SirenePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128, unique=True, verbose_name='Permission(*)')),
                ('appname', models.SlugField(blank=True, max_length=128, null=True, verbose_name='Sirene App')),
                ('displayname', models.CharField(blank=True, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('default', models.BooleanField(default=False, verbose_name='Allowed by default')),
            ],
            options={
                'verbose_name': 'Sirene Permission',
                'verbose_name_plural': 'Sirene Permissions',
                'ordering': ['keyname'],
            },
        ),
        migrations.CreateModel(
            name='SireneUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128, unique=True, verbose_name='Login/Identifier(*)')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=32, null=True, verbose_name='Mobile')),
                ('firstname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Firstname')),
                ('lastname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Lastname')),
                ('displayname', models.CharField(blank=True, max_length=500, null=True, verbose_name="Nom d'affichage")),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='External ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('want_notifications', models.BooleanField(default=True, verbose_name='Want Notifications')),
                ('want_24', models.BooleanField(default=True, verbose_name='Want 24/24')),
                ('want_sms', models.BooleanField(default=False, verbose_name='Want SMS')),
                ('want_email', models.BooleanField(default=True, verbose_name='Want Email')),
                ('secondary_email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Secondary Email')),
                ('secondary_mobile', models.CharField(blank=True, max_length=128, null=True, verbose_name='Secondary Mobile')),
            ],
            options={
                'verbose_name': 'Sirene User',
                'verbose_name_plural': 'Sirene Users',
                'ordering': ['login'],
            },
        ),
        migrations.CreateModel(
            name='SireneGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128, unique=True, verbose_name='Keyname(*)')),
                ('displayname', models.CharField(blank=True, max_length=500, null=True, verbose_name='Display name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('is_role', models.BooleanField(default=False, verbose_name='Security group (Role)')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='Built-in group')),
                ('subgroups', models.ManyToManyField(blank=True, to='app_user.sirenegroup')),
                ('permissions', models.ManyToManyField(blank=True, to='app_user.sirenepermission')),
                ('users', models.ManyToManyField(blank=True, to='app_user.sireneuser')),
            ],
            options={
                'verbose_name': 'Sirene Group',
                'verbose_name_plural': 'Sirene Groups',
                'ordering': ['keyname'],
            },
        ),
    ]
