# Generated by Django 5.0.4 on 2024-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SireneVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='Username')),
                ('user_ip', models.CharField(default='', max_length=64, verbose_name='Visitor IP')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
            ],
            options={
                'verbose_name': 'Sirene Visitor',
                'verbose_name_plural': 'Sirene Visitors',
                'ordering': ['last_login'],
            },
        ),
    ]
