# Generated by Django 5.0.4 on 2024-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_sirenevisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirenevisitor',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
