# Generated by Django 5.0.4 on 2024-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_alter_sirenevisitor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyname', models.SlugField(max_length=128, unique=True, verbose_name='Keyname')),
                ('keyvalue', models.CharField(max_length=64, verbose_name='Key value')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='is_enabled')),
                ('is_readonly', models.BooleanField(default=True, verbose_name='is_readonly')),
                ('not_after', models.DateTimeField(blank=True, null=True, verbose_name='Expire after')),
                ('time_filter', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Filter Time ranges')),
                ('ip_filter', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Filter IP ranges')),
                ('acl_filter', models.TextField(blank=True, max_length=5000, verbose_name='Security ACL')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('permissions', models.ManyToManyField(blank=True, to='app_user.sirenepermission')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['keyname'],
            },
        ),
    ]
