# Generated by Django 5.0.4 on 2024-09-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_apikey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIKey',
            new_name='SireneAPIKey',
        ),
    ]
