# Generated by Django 5.0.4 on 2024-09-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_rename_apikey_sireneapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sireneapikey',
            options={'ordering': ['keyname'], 'verbose_name': 'Sirene API Key', 'verbose_name_plural': 'Sirene API Keys'},
        ),
        migrations.RenameField(
            model_name='sireneapikey',
            old_name='last_activity',
            new_name='last_success',
        ),
    ]
