# Generated by Django 5.0.4 on 2024-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_alter_sireneapikey_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sireneapikey',
            name='last_error',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last error'),
        ),
        migrations.AlterField(
            model_name='sireneapikey',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last success'),
        ),
    ]
