# Generated by Django 5.0.4 on 2024-09-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_sireneapikey_last_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sireneapikey',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='Error count'),
        ),
        migrations.AddField(
            model_name='sireneapikey',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='Error count'),
        ),
    ]
