# Generated by Django 5.0.4 on 2024-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_sireneapikey_error_count_sireneapikey_success_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sireneapikey',
            name='success_count',
            field=models.IntegerField(default=0, verbose_name='success count'),
        ),
        migrations.AlterField(
            model_name='sirenegroup',
            name='is_role',
            field=models.BooleanField(default=False, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='sireneuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Display name'),
        ),
    ]
