# Generated by Django 5.0.4 on 2024-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_alter_sireneapikey_success_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sireneapikey',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='sirenegroup',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update'),
        ),
        migrations.AddField(
            model_name='sireneuser',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update'),
        ),
    ]
