# Generated by Django 5.0.4 on 2024-09-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_sireneapikey_last_update_sirenegroup_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sireneapikey',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
