# Generated by Django 5.0.4 on 2024-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_alter_sireneapikey_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sireneuser',
            index=models.Index(fields=['login'], name='app_user_si_login_b8ebb0_idx'),
        ),
        migrations.AddIndex(
            model_name='sireneuser',
            index=models.Index(fields=['is_enabled'], name='app_user_si_is_enab_7b9359_idx'),
        ),
        migrations.AddIndex(
            model_name='sireneuser',
            index=models.Index(fields=['displayname'], name='app_user_si_display_179714_idx'),
        ),
        migrations.AddIndex(
            model_name='sireneuser',
            index=models.Index(fields=['email'], name='app_user_si_email_878680_idx'),
        ),
    ]
