# Generated by Django 5.0.4 on 2024-10-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_sireneuser_app_user_si_login_b8ebb0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sireneapikey',
            index=models.Index(fields=['keyname'], name='app_user_si_keyname_42293d_idx'),
        ),
        migrations.AddIndex(
            model_name='sireneapikey',
            index=models.Index(fields=['is_enabled'], name='app_user_si_is_enab_cf76d3_idx'),
        ),
        migrations.AddIndex(
            model_name='sirenegroup',
            index=models.Index(fields=['keyname'], name='app_user_si_keyname_ed96f2_idx'),
        ),
        migrations.AddIndex(
            model_name='sirenegroup',
            index=models.Index(fields=['is_enabled'], name='app_user_si_is_enab_f3d760_idx'),
        ),
        migrations.AddIndex(
            model_name='sirenegroup',
            index=models.Index(fields=['is_role'], name='app_user_si_is_role_84f97c_idx'),
        ),
        migrations.AddIndex(
            model_name='sirenepermission',
            index=models.Index(fields=['keyname'], name='app_user_si_keyname_0621f9_idx'),
        ),
        migrations.AddIndex(
            model_name='sirenepermission',
            index=models.Index(fields=['appname'], name='app_user_si_appname_fe50a3_idx'),
        ),
        migrations.AddIndex(
            model_name='sirenevisitor',
            index=models.Index(fields=['username'], name='app_user_si_usernam_49437e_idx'),
        ),
    ]
