# Generated by Django 5.0.4 on 2024-12-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataclass',
            options={'ordering': ['keyname'], 'verbose_name': 'Cavaliba Data Class', 'verbose_name_plural': 'Cavaliba Data Classes'},
        ),
        migrations.AlterModelOptions(
            name='datainstance',
            options={'ordering': ['classobj', 'keyname'], 'verbose_name': 'Cavaliba Data Instance', 'verbose_name_plural': 'Cavaliba Data Instances'},
        ),
        migrations.AlterModelOptions(
            name='dataschema',
            options={'ordering': ['classobj', 'keyname', 'order'], 'verbose_name': 'Cavaliba Data Schema', 'verbose_name_plural': 'Cavaliba Data Schema'},
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_admin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_create',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_delete',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_read',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_write',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
