# Generated by Django 5.0.4 on 2024-12-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_alter_dataclass_options_alter_datainstance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataclass',
            old_name='p_write',
            new_name='p_update',
        ),
        migrations.AddField(
            model_name='datainstance',
            name='p_create',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='p_delete',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='p_read',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datainstance',
            name='p_update',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
