# Generated by Django 5.0.4 on 2024-12-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_rename_p_write_dataclass_p_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='p_create',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='p_delete',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='p_read',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='p_update',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
