# Generated by Django 5.0.4 on 2024-12-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_dataschema_p_create_dataschema_p_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataclass',
            name='role_access',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_create',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_delete',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_export',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_import',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_onoff',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_read',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_show',
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='role_update',
        ),
    ]
