# Generated by Django 5.0.4 on 2025-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_remove_datainstance_p_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschema',
            name='p_create',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='p_delete',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='p_read',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='p_update',
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_export',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='p_import',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
