# Generated by Django 5.0.4 on 2025-01-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0007_remove_dataschema_p_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname1', models.CharField(max_length=256)),
                ('instance1', models.CharField(max_length=256)),
                ('classname2', models.CharField(max_length=256)),
                ('instance2', models.CharField(max_length=256)),
                ('label1', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Cavaliba Data Link',
                'verbose_name_plural': 'Cavaliba Data Links',
                'indexes': [models.Index(fields=['classname1', 'instance1'], name='app_data_da_classna_b0593e_idx'), models.Index(fields=['classname2', 'instance2'], name='app_data_da_classna_8285e0_idx')],
            },
        ),
    ]
