# Generated by Django 5.0.4 on 2025-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0008_datalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalink',
            name='label2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
