# Generated by Django 5.0.4 on 2025-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0010_remove_datalink_label1_remove_datalink_label2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='dataformat',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('float', 'float'), ('boolean', 'boolean'), ('ipv4', 'ipv4'), ('date', 'date'), ('schema', 'schema'), ('group', 'group'), ('user', 'user'), ('datetime', 'datetime'), ('json', 'json'), ('text', 'text'), ('enumerate', 'enumerate'), ('external', 'external')], default='string', max_length=32),
        ),
    ]
