# Generated by Django 5.0.4 on 2025-01-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0011_alter_dataschema_dataformat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataLink',
        ),
    ]
